version: "3.9"
services:
  ultroid:
    container_name: ultroid
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - SESSION=${SESSION}
      - REDIS_URI=${REDIS_URI}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_CHANNEL=${LOG_CHANNEL}
    ports:
      - "8080:8080"
