#!/usr/bin/env bash
# Ultroid - UserBot
# Copyright (C) 2021-2023 TeamUltroid
#
# This file is a part of < https://github.com/TeamUltroid/Ultroid/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/TeamUltroid/Ultroid/blob/main/LICENSE/>.

echo "
            ┏┳┓╋┏┓╋╋╋╋┏┓┏┓
            ┃┃┣┓┃┗┳┳┓┏┛┃┃┃
            ┃┃┃┗┫┏┫┏┓┃┏┛┃┃
            ┗━┻━┻━┻┛┗┗┛╋┗┛

      Visit @TheUltroid for updates!!

"

# Start the health check server for Koyeb
if [ -n "$KOYEB_SERVICE_ID" ]; then
  python3 koyeb_healthcheck.py &
fi

# Start the main Ultroid bot
python3 -m pyUltroid
